# Generated by Django 5.2.4 on 2025-08-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_comment_alter_post_author_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='app.post'),
        ),
    ]
